include:
  - docker-compose.infra.yaml
services:
  agentnetwork:
    build:
      dockerfile: cmd/agentnetwork/Dockerfile
    entrypoint: ["sh", "-ce"]
    command:
      - |
        ./agentnetwork serve
    restart: always
    ports:
      - 9080:9080
    environment:
      LOG_LEVEL: debug
      HOST: 0.0.0.0
      PORT: 9080
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432/postgres?sslmode=disable&search_path=agentruntime
    links:
      - postgres:postgres.local
