# .github/workflows/lint.yml
name: Go Lint Pipeline

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code using the latest version of actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup the Go environment with Go version 1.23 using the latest version of actions/setup-go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache-dependency-path: go.sum

      # Run golangci-lint to check for lint issues
      - name: lint
        run: make lint
